<html>
    <?php echo $this->doctype(); ?>

    <head http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <?php
    echo $this->headTitle();
    echo $this->headScript();

    //add a link to the site stylesheet
    $this->headLink()->appendStylesheet($this->baseUrl().'/css/envelopes/main.css');
    echo $this->headLink();
    ?>
</head>
<body>
    <div id="pageWrapper">
        <div id="nav">
            <?php echo $this->navigation($this->mainMenuOption) ?>
        </div>
        <div id="body-wrapper">
            <div id="messages">
                <?php echo Envelopes_Model_Messages::render(); ?>
            </div>
            <div id="main">
                <?php echo $this->layout()->content; ?>
            </div>
            
    </div>
</body>

</html>