<html>
    <?php echo $this->doctype(); ?>
    
    <head http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <?php
        echo $this->headTitle();
        echo $this->headScript();
        
        //add a link to the site stylesheet
        $this->headLink()->appendStylesheet('css/envelopes/main.css');
        echo $this->headLink();
    ?>
    </head>
    <body>
        <div id="pageWrapper">
            <div id="nav">
                <?php echo get_class($this->layout()); ?>
                <?php echo $this->layout()->nav; ?>
            </div>
            <div id="main">
                <?php echo $this->layout()->content; ?>
            </div>
            <div id="footer">
                <p>Powered by the HCC Global It Department</p>
            </div>
        </div>
    </body>
    
</html>