<html>
    <?php echo $this->doctype(); ?>
    
    <head http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <?php
        echo $this->headTitle();
        echo $this->headScript();
        
        //add a link to the site stylesheet
        $this->headLink()->appendStylesheet('css/layout.css');
        echo $this->headLink();
    ?>
    </head>
    <body>
        <div id="pageWrapper">
            <div id="header">
                <h1>Zend Framework CMS</h1>
            </div>
            <div id="nav">
                <?php echo $this->layout()->nav; ?>
            </div>
            <div id="sidebar">
                <div id="subNav">
                    <?php echo $this->layout()->subNav; ?>
                </div>
                <div id="adminMenu">
                    <?php echo $this->layout()->adminMenu; ?>
                </div>
                <div id="userForm">
                    <?php echo $this->layout()->userForm; ?>
                </div>
            </div>
            <div id="main">
                <?php echo $this->layout()->content; ?>
            </div>
            <div id="footer">
                <p>Powered by the Zend Framework</p>
            </div>
        </div>
    </body>
    
</html>