<form>
<input type='button' /><label>button</label><br/>
<input type='checkbox' /><label>checkbox</label><br/>
<input type='color' /><label>color</label><br/>
<input type='date' /><label>date</label><br/>
<input type='datetime' /><label>datetime</label><br/>
<input type='datetime-local' /><label>datetime-local</label><br/>
<input type='email' /><label>email</label><br/>
<input type='file' /><label>file</label><br/>
<input type='hidden' /><label>hidden</label><br/>
<input type='image' /><label>image</label><br/>
<input type='month' /><label>month</label><br/>
<input type='number' /><label>number</label><br/>
<input type='password' /><label>password</label><br/>
<input type='radio' /><label>radio</label><br/>
<input type='range' /><label>range</label><br/>
<input type='reset' /><label>reset</label><br/>
<input type='search' /><label>search</label><br/>
<input type='submit' /><label>submit</label><br/>
<input type='tel' /><label>tel</label><br/>
<input type='text' /><label>text</label><br/>
<input type='time' /><label>time</label><br/>
<input type='url' /><label>url</label><br/>
<input type='week' /><label>week</label><br/>
</form> 