<?php
echo "<form>";
echo "<input type='button' /><label>button</label><br/>";
echo "<input type='checkbox' /><label>checkbox</label><br/>";
echo "<input type='color' /><label>color</label><br/>";
echo "<input type='date' /><label>date</label><br/>";
echo "<input type='datetime' /><label>datetime</label><br/>";
echo "<input type='datetime-local' /><label>datetime-local</label><br/>";
echo "<input type='email' /><label>email</label><br/>";
echo "<input type='file' /><label>file</label><br/>";
echo "<input type='hidden' /><label>hidden</label><br/>";
echo "<input type='image' /><label>image</label><br/>";
echo "<input type='month' /><label>month</label><br/>";
echo "<input type='number' /><label>number</label><br/>";
echo "<input type='password' /><label>password</label><br/>";
echo "<input type='radio' /><label>radio</label><br/>";
echo "<input type='range' /><label>range</label><br/>";
echo "<input type='reset' /><label>reset</label><br/>";
echo "<input type='search' /><label>search</label><br/>";
echo "<input type='submit' /><label>submit</label><br/>";
echo "<input type='tel' /><label>tel</label><br/>";
echo "<input type='text' /><label>text</label><br/>";
echo "<input type='time' /><label>time</label><br/>";
echo "<input type='url' /><label>url</label><br/>";
echo "<input type='week' /><label>week</label><br/>";
echo "</form>"; 

$form = new \Pform\Form('house');

$form->setLegend('Your address');
$e1 = new \Pform\Input_Text('your-name','Your name');

$form->appendElement($e1);
$e2 = new \Pform\Input_Text('street','Street name');

$form->appendElement($e2);
$button = new Pform\Button('submit','Submit');

$fieldset = new Pform\Fieldset('fieldset-1');
$fieldset->setLegend('Nice Legend');
$textarea = new \Pform\Textarea('textarea','Comments');
$user = new \Pform\Input_Text('other-text','User');

$fieldset->appendElement($user);
$fieldset->appendElement($textarea);
$form->appendElement($fieldset);

$form->appendElement($button);


echo $form;
    