<?php
echo "<a href='".$this->baseUrl()."/envelopes/test/all-types'>All form types</a>";
echo Utilities\Utilities::pre($this->params);
$form = new \Pform\Form('form', 'This is a form');
$username = new \Pform\Input_Text('username', 'Username');
$username->setValue('Text')->setPlaceholder('Username')->setRequired();
$password = new \Pform\Input_Text('password','Password');
$password->setRequired();
$form->addElement($username);
$form->addElement($password);

$fieldset = new Pform\Fieldset('blah','Address info');
$street = new \Pform\Input_Text('street', 'Street');
$fieldset->addElement($street);
$postalcode = new \Pform\Input_Text('postal-code','Postal Code');
$fieldset->addElement($postalcode);
$form->addElement($fieldset);
$form->addElement(new \Pform\Button('submit', 'Submit'));

if(isset($this->params)){
    $form->setValues($this->params);
}
echo $form->render();
    
echo Utilities\Utilities::pre($form->getValues());
