<div class="uk-grid">
<div class='uk-width-2-3'>
    <div class='uk-panel uk-panel-box uk-panel-box-secondary'>
    <h3 class="uk-panel-title"><i class='uk-icon-envelope-o'></i> Envelopes</h3>
    <?php echo $this->openEnvelopes(); ?>
    </div>
</div>
<div class="uk-width-1-3">
    <div class='uk-panel uk-panel-box uk-panel-box-secondary'>
        <h3 class="uk-panel-title"><i class='uk-icon-cog'></i> Config</h3>
            <?php echo $this->config(); ?>
    </div>
    
    <div class='uk-panel uk-panel-box uk-panel-box-secondary'>
    <h3 class="uk-panel-title"><i class='uk-icon-birthday-cake'></i> Birthdays</h3>
    <?php echo $this->nextBirthdays(); ?>
    </div>
</div>
</div>